---
abstract: 'unescape XML entities in Template Toolkit'
author:
  - 'Paul Driver <frodwith@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-XML-Unescape
requires:
  HTML::Entities: 0
  Template: 0
version: 0.02
